"use client";

/**
 * ⛔ THE MARK BENCH'S CLIENT HALF — D-088. PASS 1 (7 October 2026): THE SHAPE ONLY, IN CLAY.
 * Plan: `live-work/desk-mark-pass1-mesh-plan-7-october.md` (version 2, amended per the Architect, approved by Carl).
 *
 * ⛔ WHY CLAY. Chunk 1 (3 October) built the mesh, the gold and the studio light at once; the gold and the light dressed
 * a torn junction on the b and it passed as "close". Carl, 7 October: *"mesh, material and lights"* — one pass at a time,
 * each approved by eye before the next (the blue Next step button's process, D-030). Pass 1: *"make it a simple grey
 * material and light it so it brings out the geometry… get the shape right."* The gold, the Lightformer studio and the
 * room reflection are GONE from this bench until their passes; `logo-mark-material.ts` stays on disk, unused.
 *
 * ⛔ THE MODES SEE DIFFERENT THINGS (Architect A4). `clay`, `zebra` and `normals` shade with the COMPUTED vertex normals —
 * and a computed normal can smooth over a crease the triangles really have. **`flat` lights the TRIANGLES**
 * (`flatShading`), so only `flat` shows the mesh as built. Judge a crease in `flat`; judge continuity in `zebra`.
 *
 * ⛔ SHADOWS ARE A SWITCH (Architect, should-fix): self-shadow on a smooth surface can stripe (acne) or float (a gap at a
 * foot), and either reads as a fault in the shape. Off isolates the light from the geometry.
 *
 * ⛔ THE JUNCTION VIEW'S CAMERA IS A FIXED CONSTANT (A6): the before (3 October mesh) and after frames share one viewpoint.
 * Its window is `LOGO_JUNCTION.window`, generated by the extract script — never typed by hand.
 *
 * ⛔ RENDERER PARITY WITH `/about` is kept (ACES, sRGB, antialias, alpha, DPR 1–2, soft shadows) — not because clay needs
 * it, but so the material and light passes inherit a bench that already matches the room (Architect A5, chunk 1).
 * ⛔ THE FRONT VIEW IS FRAMED BY THE OUTLINE'S OWN NORMALISATION TRANSFORM (A4); the target overlay is a DOM image (A5).
 * ⛔ THE BUILD IS TIMED IN AN EFFECT (A11). Stats on `window.__logoBench` for the live-work scripts.
 */
import { useEffect, useMemo, useRef, useState } from "react";
import Image from "next/image";
import * as THREE from "three";
import { Canvas, useFrame } from "@react-three/fiber";
import { OrbitControls, OrthographicCamera, PerspectiveCamera } from "@react-three/drei";
import goldTarget from "../../brand-assets/logo/c2b-logo-gold-relit-alpha-1671.png";
import {
  buildLogoMarkGeometry, LOGO_MARK_DEFAULTS, SRC_PX, windowReadouts,
  type LogoMarkParams, type LogoMarkStats, type WindowReadouts,
} from "./logo-mark-geometry";
import { LOGO_JUNCTION, LOGO_OUTLINE_SOURCE as SRC } from "./logo-mark-outline";

export type LogoBenchFlags = {
  view?: string; mask?: boolean; overlay?: number; mode?: string; wire?: boolean; shadows?: boolean; az?: number; el?: number;
};

const VIEWS = ["front", "oblique", "junction", "turntable", "side", "below", "roomsize"] as const;
type View = (typeof VIEWS)[number];
const MODES = ["clay", "flat", "zebra", "normals"] as const;
type Mode = (typeof MODES)[number];

/** ⚠ PLACEHOLDER — chunk 2 sets the real height in room millimetres from the plate target (144 plate px). */
const PLACEHOLDER_HEIGHT_MM = 180;
/** The room-size view: the mark's approved size on Carl's screen, ~70 CSS px tall (D-088, 3 October). */
const ROOMSIZE_MARK_CSS_PX = 70;

/** Clay: mid-grey, matte, no metal — the shape and nothing else. */
const CLAY = { color: "#8a8a8a", roughness: 0.6 } as const;
/** The key light's starting direction — upper-left, low, raking. Degrees: azimuth from the camera axis (negative =
 *  left), elevation above the mark's horizontal. ⚠ Starting points for Carl's eye. */
const KEY_DEFAULT = { az: -55, el: 32 };

/**
 * ⛔ THE JUNCTION CAMERA — fixed (A6), in mark units, scaled by the mark's height. Aimed at the centre of the generated
 * junction window, from the front-right and a little above, framing the window. Changing it invalidates the 7 October
 * baseline frames (`live-work/logo-pass1-baseline-7-october.md`).
 */
const JW = LOGO_JUNCTION.window;
const JUNCTION_TARGET: [number, number, number] = [(JW.x0 + JW.x1) / 2, (JW.y0 + JW.y1) / 2, 0.05];
const JUNCTION_CAMERA: [number, number, number] = [JUNCTION_TARGET[0] + 0.42, JUNCTION_TARGET[1] + 0.3, 1.0];

type Built = { geometry: THREE.BufferGeometry; stats: LogoMarkStats; ms: number; junction: WindowReadouts };

declare global {
  interface Window {
    __logoBench?: {
      ready: boolean; stats: LogoMarkStats; buildMs: number; params: LogoMarkParams; view: View; mask: boolean; mode: Mode;
      junction: WindowReadouts; junctionWindow: typeof JW; junctionCamera: { position: number[]; target: number[] };
    };
  }
}

function Turntable({ on, children }: { on: boolean; children: React.ReactNode }) {
  const group = useRef<THREE.Group>(null);
  useFrame((_, dt) => {
    if (on && group.current) group.current.rotation.y += dt * 0.35;
  });
  return <group ref={group}>{children}</group>;
}

/**
 * The shape light: a raking key (the only shadow caster), a weak opposite fill, a rim from behind and above, a low
 * hemisphere so no face goes fully black. ⛔ Shadow settings, stated (should-fix): 2048² map, an orthographic frustum
 * fitted round the mark (±1.2 heights), bias −0.0005, normalBias ½ a grid step — starting values; the switch is the test.
 */
function ShapeLight({ S, az, el, shadows, normalBias }: { S: number; az: number; el: number; shadows: boolean; normalBias: number }) {
  const r = (d: number) => (d * Math.PI) / 180;
  const dir: [number, number, number] = [Math.sin(r(az)) * Math.cos(r(el)), Math.sin(r(el)), Math.cos(r(az)) * Math.cos(r(el))];
  const C = [0, 0.5 * S, 0];
  const at = (k: number, d: [number, number, number]): [number, number, number] => [C[0] + d[0] * k, C[1] + d[1] * k, C[2] + d[2] * k];
  const light = useRef<THREE.DirectionalLight>(null);
  useEffect(() => {
    const l = light.current;
    if (!l) return;
    l.target.position.set(C[0], C[1], C[2]);
    l.target.updateMatrixWorld();
  });
  return (
    <>
      <hemisphereLight args={["#ffffff", "#3a3a3a", 0.35]} />
      <directionalLight
        key={shadows ? "shadowed" : "plain"}
        ref={light}
        position={at(4 * S, dir)}
        intensity={2.4}
        castShadow={shadows}
        shadow-mapSize={[2048, 2048]}
        shadow-bias={-0.0005}
        shadow-normalBias={normalBias}
        shadow-camera-left={-1.2 * S}
        shadow-camera-right={1.2 * S}
        shadow-camera-top={1.2 * S}
        shadow-camera-bottom={-1.2 * S}
        shadow-camera-near={0.5 * S}
        shadow-camera-far={8 * S}
      />
      <directionalLight position={at(4 * S, [-dir[0] * 0.8, 0.15, 0.6])} intensity={0.35} />
      <directionalLight position={at(4 * S, [0.2, 0.7, -0.7])} intensity={0.9} />
    </>
  );
}

/** Zebra: a matcap of hard horizontal stripes — the stripes follow the view-space normal, so a crease breaks or kinks
 *  them and a smooth join carries them through. ⚠ It shades with the COMPUTED normals; `flat` is the check on those. */
function makeZebra() {
  const c = document.createElement("canvas");
  c.width = c.height = 512;
  const g = c.getContext("2d")!;
  const bands = 14;
  for (let i = 0; i < bands; i++) {
    g.fillStyle = i % 2 ? "#f2f2f2" : "#151515";
    g.fillRect(0, (i * 512) / bands, 512, 512 / bands + 1);
  }
  const t = new THREE.CanvasTexture(c);
  t.colorSpace = THREE.SRGBColorSpace;
  return new THREE.MeshMatcapMaterial({ matcap: t });
}

function Slider({ label, value, min, max, step, onChange, fmt }: {
  label: string; value: number; min: number; max: number; step: number; onChange: (v: number) => void; fmt?: (v: number) => string;
}) {
  return (
    <label className="flex items-center gap-2">
      <span className="w-24">{label}</span>
      <input type="range" min={min} max={max} step={step} value={value} onChange={(e) => onChange(Number(e.target.value))} className="w-36" />
      <span className="tabular-nums text-neutral-400 w-20">{fmt ? fmt(value) : value.toFixed(3)}</span>
    </label>
  );
}

export default function LogoBench({ flags }: { flags: LogoBenchFlags }) {
  const [view, setView] = useState<View>(VIEWS.includes(flags.view as View) ? (flags.view as View) : "oblique");
  const [mode, setMode] = useState<Mode>(MODES.includes(flags.mode as Mode) ? (flags.mode as Mode) : "clay");
  const [mask, setMask] = useState(!!flags.mask);
  const [wire, setWire] = useState(!!flags.wire);
  const [shadows, setShadows] = useState(flags.shadows ?? true);
  const [az, setAz] = useState(Number.isFinite(flags.az) ? (flags.az as number) : KEY_DEFAULT.az);
  const [el, setEl] = useState(Number.isFinite(flags.el) ? (flags.el as number) : KEY_DEFAULT.el);
  const [overlay, setOverlay] = useState(flags.overlay ?? 0);
  const [heightMm, setHeightMm] = useState(PLACEHOLDER_HEIGHT_MM);
  const [geo, setGeo] = useState<LogoMarkParams>({ ...LOGO_MARK_DEFAULTS });
  const [built, setBuilt] = useState<Built | null>(null);

  const params = useMemo(() => ({ ...geo, scale: heightMm }), [geo, heightMm]);

  // build — debounced, timed here, never in render
  useEffect(() => {
    const id = window.setTimeout(() => {
      const t0 = performance.now();
      const r = buildLogoMarkGeometry(params);
      const ms = performance.now() - t0;
      // the window readouts are front-only, above the lip
      setBuilt({ ...r, ms, junction: windowReadouts(r.geometry, JW, params.scale, r.stats.lipHeight) });
    }, 200);
    return () => window.clearTimeout(id);
  }, [params]);
  useEffect(() => () => built?.geometry.dispose(), [built]);
  useEffect(() => {
    if (!built) return;
    window.__logoBench = {
      ready: true, stats: built.stats, buildMs: built.ms, params, view, mask, mode,
      junction: built.junction, junctionWindow: JW,
      junctionCamera: { position: JUNCTION_CAMERA, target: JUNCTION_TARGET },
    };
  }, [built, params, view, mask, mode]);

  const clay = useMemo(() => new THREE.MeshStandardMaterial({ ...CLAY, metalness: 0 }), []);
  const flat = useMemo(() => new THREE.MeshStandardMaterial({ ...CLAY, metalness: 0, flatShading: true }), []);
  const zebra = useMemo(() => (typeof document === "undefined" ? null : makeZebra()), []);
  const normals = useMemo(() => new THREE.MeshNormalMaterial(), []);
  const white = useMemo(() => new THREE.MeshBasicMaterial({ color: "#ffffff", toneMapped: false }), []);
  const wireMat = useMemo(() => new THREE.MeshBasicMaterial({ color: "#000000", wireframe: true, transparent: true, opacity: 0.3 }), []);
  useEffect(() => () => {
    for (const m of [clay, flat, normals, white, wireMat]) m.dispose();
    zebra?.matcap?.dispose();
    zebra?.dispose();
  }, [clay, flat, zebra, normals, white, wireMat]);
  const material = mask ? white : mode === "flat" ? flat : mode === "zebra" && zebra ? zebra : mode === "normals" ? normals : clay;

  const S = heightMm;
  const front = view === "front" || view === "roomsize";
  // the frustum that covers the source image exactly, in model units
  const frame = {
    left: (-SRC.originPx.x / SRC.pxPerUnit) * S,
    right: ((SRC.widthPx - SRC.originPx.x) / SRC.pxPerUnit) * S,
    top: (SRC.originPx.y / SRC.pxPerUnit) * S,
    bottom: ((SRC.originPx.y - SRC.heightPx) / SRC.pxPerUnit) * S,
  };
  const scaled = (v: [number, number, number]): [number, number, number] => [v[0] * S, v[1] * S, v[2] * S];
  const target: [number, number, number] = view === "junction" ? scaled(JUNCTION_TARGET) : [0, 0.5 * S, 0.04 * S];
  const persp: Record<Exclude<View, "front" | "roomsize">, [number, number, number]> = {
    oblique: [0.95 * S, 0.85 * S, 1.9 * S],
    junction: scaled(JUNCTION_CAMERA),
    turntable: [0, 0.55 * S, 2.6 * S],
    side: [2.4 * S, 0.2 * S, 0.12 * S],
    below: [0.35 * S, -0.75 * S, 1.3 * S],
  };
  const panelStyle: React.CSSProperties =
    view === "roomsize"
      ? { height: (ROOMSIZE_MARK_CSS_PX * SRC.heightPx) / SRC.pxPerUnit, width: (ROOMSIZE_MARK_CSS_PX * SRC.widthPx) / SRC.pxPerUnit }
      : { aspectRatio: `${SRC.widthPx} / ${SRC.heightPx}` };
  const st = built?.stats;
  const jr = built?.junction;
  const n = (v: number | undefined, d = 2) => (v === undefined ? "…" : v.toFixed(d));
  const select = "bg-neutral-900 border border-neutral-700 px-2 py-1";

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-center gap-x-6 gap-y-2 text-sm">
        <label className="flex items-center gap-2">
          view
          <select value={view} onChange={(e) => setView(e.target.value as View)} className={select}>
            {VIEWS.map((v) => (<option key={v} value={v}>{v === "roomsize" ? "room size (~70 CSS px)" : v}</option>))}
          </select>
        </label>
        <label className="flex items-center gap-2">
          mode
          <select value={mode} onChange={(e) => setMode(e.target.value as Mode)} className={select}>
            <option value="clay">clay</option>
            <option value="flat">flat — the triangles as built</option>
            <option value="zebra">zebra — surface continuity</option>
            <option value="normals">normals</option>
          </select>
        </label>
        <label className="flex items-center gap-2"><input type="checkbox" checked={wire} onChange={(e) => setWire(e.target.checked)} /> wireframe</label>
        <label className="flex items-center gap-2"><input type="checkbox" checked={shadows} onChange={(e) => setShadows(e.target.checked)} /> shadows</label>
        <label className="flex items-center gap-2"><input type="checkbox" checked={mask} onChange={(e) => setMask(e.target.checked)} /> mask (measurement)</label>
        {front && !mask && (
          <Slider label="target overlay" value={overlay} min={0} max={1} step={0.05} onChange={setOverlay} fmt={(v) => v.toFixed(2)} />
        )}
      </div>

      <div
        className={`relative border border-neutral-700 ${view === "roomsize" ? "" : "w-full"}`}
        style={{ ...panelStyle, background: mask ? "#000000" : "#121212", maxWidth: view === "roomsize" ? undefined : "100%" }}
      >
        <Canvas key={front ? "ortho" : `persp-${view}`} gl={{ antialias: true, alpha: true }} dpr={[1, 2]} shadows="soft" frameloop="always">
          {front ? (
            <OrthographicCamera makeDefault position={[0, 0, 10 * S]} near={0.1} far={40 * S} {...frame} manual />
          ) : (
            <PerspectiveCamera makeDefault position={persp[view as keyof typeof persp]} fov={30} near={S * 0.01} far={S * 40} />
          )}
          {!front && <OrbitControls target={target} enableDamping={false} />}
          {!mask && <ShapeLight S={S} az={az} el={el} shadows={shadows} normalBias={0.5 * geo.gridStep * S} />}
          {built && (
            <Turntable on={view === "turntable"}>
              <mesh geometry={built.geometry} material={material} castShadow={shadows && !mask} receiveShadow={shadows && !mask} />
              {wire && !mask && <mesh geometry={built.geometry} material={wireMat} />}
            </Turntable>
          )}
        </Canvas>
        {front && !mask && overlay > 0 && (
          <Image
            src={goldTarget}
            alt="Carl's gold target, the trace source's cut-out, in the same framing"
            fill
            unoptimized
            className="pointer-events-none select-none"
            style={{ opacity: overlay, objectFit: "fill" }}
          />
        )}
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-x-10 gap-y-2 text-sm">
        <div className="space-y-2">
          <div className="text-neutral-500">light — rake it across a feature</div>
          <Slider label="key azimuth" value={az} min={-90} max={90} step={1} onChange={setAz} fmt={(v) => `${v}°`} />
          <Slider label="key elevation" value={el} min={0} max={85} step={1} onChange={setEl} fmt={(v) => `${v}°`} />
          <div className="text-neutral-500 pt-2">form — ⚠ starting points for Carl&apos;s eye</div>
          <Slider label="height mm" value={heightMm} min={60} max={600} step={10} onChange={setHeightMm} fmt={(v) => `${v} (placeholder)`} />
          <Slider label="bevel width" value={geo.bevelW / SRC_PX} min={4} max={40} step={0.5} onChange={(v) => setGeo({ ...geo, bevelW: v * SRC_PX })} fmt={(v) => `${v.toFixed(1)} src px`} />
          <Slider label="bevel angle" value={(Math.atan(geo.bevelRise) * 180) / Math.PI} min={20} max={70} step={1} onChange={(v) => setGeo({ ...geo, bevelRise: Math.tan((v * Math.PI) / 180) })} fmt={(v) => `${v.toFixed(0)}° from flat`} />
          <Slider label="edge round" value={geo.edgeRound / SRC_PX} min={0} max={20} step={0.5} onChange={(v) => setGeo({ ...geo, edgeRound: v * SRC_PX })} fmt={(v) => (v === 0 ? "sharp" : `${v.toFixed(1)} src px`)} />
          <Slider label="depth" value={geo.depth / SRC_PX} min={15} max={90} step={1} onChange={(v) => setGeo({ ...geo, depth: v * SRC_PX })} fmt={(v) => `${v.toFixed(0)} src px`} />
          <Slider label="lip" value={geo.lipW / SRC_PX} min={0.5} max={6} step={0.25} onChange={(v) => setGeo({ ...geo, lipW: v * SRC_PX })} fmt={(v) => `${v.toFixed(2)} src px`} />
          <Slider label="grid step" value={geo.gridStep * SRC.pxPerUnit} min={1} max={6} step={0.25} onChange={(v) => setGeo({ ...geo, gridStep: v / SRC.pxPerUnit })} fmt={(v) => `${v.toFixed(2)} src px`} />
          <Slider label="round rings" value={geo.roundRings} min={1} max={24} step={1} onChange={(v) => setGeo({ ...geo, roundRings: v })} fmt={(v) => `${v}`} />
          <Slider label="chamfer rings" value={geo.chamferRings} min={1} max={12} step={1} onChange={(v) => setGeo({ ...geo, chamferRings: v })} fmt={(v) => `${v}`} />
        </div>
        <div className="space-y-1 tabular-nums text-neutral-300">
          <div className="text-neutral-500">readouts — from the BUILT mesh</div>
          <div>build {n(built?.ms, 0)} ms · {st?.vertices ?? "…"} vertices · {st?.triangles ?? "…"} triangles</div>
          <div>open edges (welded) {st?.openEdges ?? "…"} · non-manifold {st?.nonManifoldEdges ?? "…"} · NaN {st?.nanValues ?? "…"}</div>
          <div>flipped band triangles {st?.flippedBandTriangles ?? "…"} · ring clamps {st?.ringClamps ?? "…"}</div>
          <div>face {n(st && st.crestHeight / SRC_PX, 1)} src px deep · lip at {n(st && st.lipHeight / SRC_PX, 1)} · bevel used {n(st && st.bevelUsed / SRC_PX, 1)} src px</div>
          <div>max normal angle — face {n(st?.maxNormalAngleFaceDeg, 2)}° (must be ~0: the face is flat)</div>
          <div>— whole front {n(st?.maxNormalAngleDeg, 1)}° (mitres at corners) · edges &gt; 30° {st?.edgesOver30Deg ?? "…"}</div>
          <div>max interior z-step {n(st?.maxGridZStepSourcePx, 3)} source px (must be 0: the grid carries only the flat)</div>
          <div className="text-neutral-500 pt-2">junction window (generated) — front triangles above the lip</div>
          <div>{jr?.triangles ?? "…"} triangles · computed-normal angle max {n(jr?.maxNormalAngleDeg, 1)}°</div>
          <div>dihedral (the triangles) max {n(jr?.maxDihedralDeg, 1)}° · 99th {n(jr?.p99DihedralDeg, 1)}°</div>
        </div>
      </div>
    </div>
  );
}
